python split_bin_check.py --nbins 10
python split_bin_check.py --nbins 20
python split_bin_check.py --nbins 30
python split_bin_check.py --nbins 40
python split_bin_check.py --nbins 50
python split_bin_check.py --nbins 60
python split_bin_check.py --nbins 70
python split_bin_check.py --nbins 80
python split_bin_check.py --nbins 90
python split_bin_check.py --nbins 100
